# Generated by Django 3.0.8 on 2020-07-13 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather_searches',
            options={'verbose_name_plural': 'Weather-Searches'},
        ),
    ]
